name: PluginDevTools
version: '1.21.10-R0.3-SNAPSHOT'

main: de.api.devtools.MinecraftDevToolPlugin

api-version: '1.21'
load: STARTUP
authors: [_XCuzImSmart_]

commands:
  bedwars:
    aliases: [bw]
