name: PluginDevTools
version: 1.2.1-SNAPSHOT

### means the spigot version, this plugin is compatible with.
api-version: 1.8.8
description: Custom Library for Minecraft Plugin Programming using Spigot/Bukkit API. I upload code Files for my Plugins you can copy and use it in your Plugin!
author: _XCuzImSmart_

main: de.api.plugins.MinecraftDevToolPlugin

